#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check prettier standards
npm run check-format ||
(
  echo "Prettier check failed. Run npm run format to fix and commit again."
  false;
)

# Check tsconfig standards
npm run check-types ||
(
  echo "TypeScript check failed"
  false;
)

# Check Eslint standards
npm run check-lint ||
(
  echo "Eslint check failed"
  false;
)

# Everything passes
echo "All checks passed"

# npm run build